language: swift
osx_image: xcode11
notifications:
  email: false

before_install:
  - brew update
  - gem install bundler
  - bundle
  - cd Example/
  - pod install
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
  - set -o pipefail
  - xcodebuild -workspace Example.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
